swagger: "2.0"
info:
  title: TestHello
  x-ibm-name: testhello
  version: 1.0.0
schemes:
- https
basePath: /testhello
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
    - set-variable:
        version: 2.0.0
        title: set-variable
        actions:
        - set: message.body
          value: Hi there!!
          type: string
    catch: []
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication:
    certificate: false
paths:
  /{anything}:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      consumes: []
      produces: []
      parameters:
      - name: anything
        in: path
        required: true
        description: any string
        type: string
